version: '3'
services:
  tasker:
    image: tasker
    build: .
    ports:
      - "7540:7540"     
    environment:
      - TODO_PORT=7540
      - TODO_DBFILE=/app/scheduler.db
    volumes:
      - ./scheduler.db:/app/scheduler.db